[dev]
  framework = "#static"

[build]
  command = "echo No build for this site, we are living on the edge"
  publish = "public"

[context.production]
  environment = { MY_IMPORTANT_VARIABLE = "this is a very important secret" }

[[edge_functions]]
  path = "/streaming"
  function = "streaming"

[[edge_functions]]
  path = "/hello"
  function = "hello"

[[redirects]]
  from = "/img/og/:text"
  to = "https://res.cloudinary.com/netlify/image/upload/c_fit,g_west,h_400,co_rgb:FFFFFFFF,l_text:netlify.com:Pacaembu-Bold.ttf_57::text,w_1053,x_46/v1619123320/netlify.com/default-og-background-learn-more.png"
  status = 200






